#!/usr/bin/env bash
# install/host/5-broker-service.sh — HOST (broker machine) step 5, run as root
# Installs the broker as a HARDENED systemd service running as hestia-broker. Deploys the current
# broker.py + brokerd.py from the repo, writes the site EnvironmentFile (with the bot token) at a
# root-only path, installs the sandboxed unit, and (structurally) verifies. Does NOT auto-start
# unless HESTIA_START=1 — start it during live-deploy after the mover + target pieces are confirmed.
#
# Installs FROM the repo:  broker/broker.py, broker/brokerd.py, broker/hestia-broker.service.
# The secret Telegram bot token is prompted for (or read from $TELEGRAM_BROKER_BOT_TOKEN) and written
# ONLY into /etc/hestia-broker/broker.env (0600 root:root; systemd reads it as root before dropping
# privilege). It is never committed and never printed.
# Reversible: systemctl disable --now hestia-broker; rm -f /etc/systemd/system/hestia-broker.service
#             /etc/hestia-broker/broker.env /usr/local/lib/hestia/broker*.py
set -euo pipefail

# --- load site config (values may also come straight from the environment) ---
HESTIA_ENV="${HESTIA_ENV:-$(cd "$(dirname "$0")" && pwd)/../../config/hestia.env}"
[[ -f "$HESTIA_ENV" ]] && . "$HESTIA_ENV"

REPO="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"

BROKER=hestia-broker
LIB=/usr/local/lib/hestia
ETC=/etc/hestia-broker
ENVFILE="$ETC/broker.env"
SRC_UNIT="$REPO/broker/hestia-broker.service"
UNIT=/etc/systemd/system/hestia-broker.service

# Required site values (fail fast with a clear message if unset).
OWNER_ID="${HESTIA_OWNER_ID:?set HESTIA_OWNER_ID in config/hestia.env}"
TARGET_HOST="${HESTIA_TARGET_HOST:?set HESTIA_TARGET_HOST in config/hestia.env}"
SPOOL="${HESTIA_SPOOL:-/var/lib/hestia-spool}"
# OWNER_UNIX_USER is optional; it enables elevation (must match the target wrapper's ALLOWED_RUNAS).
ELEV_RUNAS="${OWNER_UNIX_USER:-}"

[[ $EUID -eq 0 ]] || { echo "run as root (sudo)"; exit 1; }
id "$BROKER" &>/dev/null || { echo "FATAL: $BROKER missing (run 1-users.sh)"; exit 1; }
command -v python3 >/dev/null || { echo "FATAL: python3 missing"; exit 1; }
for f in broker.py brokerd.py; do [[ -f "$REPO/broker/$f" ]] || { echo "FATAL: broker/$f not found in repo"; exit 1; }; done
[[ -f "$SRC_UNIT" ]] || { echo "FATAL: hestia-broker.service not found at $SRC_UNIT"; exit 1; }

echo "== deploy broker code =="
install -d -o root -g root -m 0755 "$LIB"
install -o root -g root -m 0755 "$REPO/broker/broker.py"  "$LIB/broker.py"
install -o root -g root -m 0755 "$REPO/broker/brokerd.py" "$LIB/brokerd.py"

echo "== obtain the Telegram bot token (secret) =="
TOKEN="${TELEGRAM_BROKER_BOT_TOKEN:-}"
if [[ -z "$TOKEN" ]]; then
  # Read silently from the terminal; never echo it, never store it in the environment/history.
  read -r -s -p "Enter the broker Telegram bot token (input hidden): " TOKEN < /dev/tty
  echo
fi
[[ -n "$TOKEN" ]] || { echo "FATAL: no bot token provided (set \$TELEGRAM_BROKER_BOT_TOKEN or type it)."; exit 1; }

echo "== write site EnvironmentFile (root-only; contains the secret token) =="
install -d -o root -g root -m 0755 "$ETC"
# Write to a temp file with a tight umask, then move into place at 0600 root:root.
umask 077
tmp="$(mktemp "$ETC/.broker.env.XXXXXX")"
{
  echo "# /etc/hestia-broker/broker.env — generated by install/host/5-broker-service.sh"
  echo "# 0600 root:root. Contains the SECRET Telegram bot token. Do NOT commit or copy."
  echo "TELEGRAM_BROKER_BOT_TOKEN=$TOKEN"
  echo "HESTIA_OWNER_ID=$OWNER_ID"
  echo "HESTIA_TARGET_HOST=$TARGET_HOST"
  echo "HESTIA_SPOOL=$SPOOL"
  [[ -n "$ELEV_RUNAS" ]] && echo "HESTIA_ELEV_RUNAS=$ELEV_RUNAS"
  # Optional broker tuning passthroughs (only emitted if set in config).
  for v in HESTIA_SESSION_SECS HESTIA_CMD_SECS HESTIA_SESSION_ASK_SECS HESTIA_EXEC_TIMEOUT \
           HESTIA_MAX_INFLIGHT HESTIA_MAX_PENDING HESTIA_SESSION_CMD_BUDGET; do
    val="${!v:-}"; [[ -n "$val" ]] && echo "$v=$val"
  done
} > "$tmp"
chown root:root "$tmp"; chmod 0600 "$tmp"
mv -f "$tmp" "$ENVFILE"
TOKEN=""   # drop the secret from this shell asap

echo "== install hardened systemd unit =="
install -o root -g root -m 0644 "$SRC_UNIT" "$UNIT"
systemctl daemon-reload

echo
echo "== VERIFY (structural) =="
fail=0
python3 -c "import ast; ast.parse(open('$LIB/brokerd.py').read()); ast.parse(open('$LIB/broker.py').read())" \
  && echo "-- broker code parses" || { echo "  ERROR: broker code parse fail"; fail=1; }
# EnvironmentFile perms: root-only, contains the secret
perm=$(stat -c '%a %U:%G' "$ENVFILE"); echo "-- broker.env: $perm"
[[ "$perm" == "600 root:root" ]] || { echo "  ERROR: broker.env perms wrong (want 600 root:root)"; fail=1; }
# token present but never echoed
grep -q '^TELEGRAM_BROKER_BOT_TOKEN=' "$ENVFILE" && echo "-- token line present (value not shown)" || { echo "  ERROR: token line missing"; fail=1; }
# fence still intact
for g in lxd docker sudo wheel; do id -nG "$BROKER" | tr ' ' '\n' | grep -qx "$g" && { echo "  FENCE VIOLATION: $BROKER in $g"; fail=1; }; done
# unit sanity
systemd-analyze verify "$UNIT" 2>&1 | grep -v '^$' | sed 's/^/   [unit] /' || true

echo
if [[ $fail -eq 0 ]]; then
  echo "HOST STEP 5 broker install: OK (unit installed, NOT started)."
  if [[ "${HESTIA_START:-0}" == "1" ]]; then
    echo "== HESTIA_START=1 -> starting =="; systemctl enable --now hestia-broker.service; sleep 3
    systemctl is-active --quiet hestia-broker.service && { echo "-- active"; journalctl -u hestia-broker -n 8 --no-pager | sed 's/^/     /'; } \
      || { echo "  ERROR: not active"; journalctl -u hestia-broker -n 25 --no-pager | sed 's/^/     /'; exit 2; }
  else
    echo "To start (live-deploy phase):  sudo HESTIA_START=1 bash $0   OR   sudo systemctl enable --now hestia-broker"
  fi
else
  echo "HOST STEP 5 broker install: PROBLEMS above" >&2; exit 2
fi
